import { Divider } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Navbar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Divider orientation='horizontal' borderColor='#d4ff1e'/>
      <Header />
      <Divider orientation='horizontal' borderColor='#d4ff1e'/>
      <Footer />

    </div>
  )
}

export default Home
